services:
  - type: web
    name: organise-simple-standalone
    env: node
    region: singapore 
    buildCommand: npm install && npm run build
    startCommand: node dist/src/main
    nodeVersion: 22.14.0
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
      - key: PORT
        value: 3000
